
name: AtProtoSync
on: 
  schedule: 
    - cron: '0,30 0-23 * * *'
  workflow_dispatch: 
jobs: 
  SyncAtProto: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@main
      - name: Use Websocket Action
        uses: PowerShellWeb/Websocket@main
        id: WebSocket

